WITH USERS AS( 
    SELECT DISTINCT 
        authorFullID
    FROM `redditcuddledata.Reddit6MonthsScrapedData.redditcuddledata6` AS UNIQUE_AUTHORS
),
USERS_AND_POST_FREQUENCIES AS (
    SELECT 
        LINKFLAIRCSS AS FLAIR,
        COUNT(USERS.authorFullID) AS POST_FREQUENCY,
        USERS.authorFullID AS AUTHOR
    FROM `redditcuddledata.Reddit6MonthsScrapedData.redditcuddledata6` AS REDDIT_DATA
    INNER JOIN USERS
        ON REDDIT_DATA.authorFullID = USERS.authorFullID
        GROUP BY FLAIR, AUTHOR
)
SELECT 
    UPPER(USERS_AND_POST_FREQUENCIES.FLAIR) AS FLAIR,
    COUNT(UPPER(USERS_AND_POST_FREQUENCIES.FLAIR)) AS FLAIR_FREQUENCY
FROM USERS_AND_POST_FREQUENCIES
    GROUP BY FLAIR